# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lesgo < Formula
  desc "WhatsApp-style CLI chat with E2EE."
  homepage "https://github.com/XplnHUB/Les-Go"
  version "1.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/XplnHUB/Les-Go/releases/download/v1.1.0/Les-Go_1.1.0_darwin_amd64.tar.gz"
      sha256 "5e4dfb51c504e4a52c0e38bd1b944ab9334f7c7af0771e71f9829c6e1b5b353a"

      define_method(:install) do
        bin.install "lesgo"
        bin.install "server_bin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/XplnHUB/Les-Go/releases/download/v1.1.0/Les-Go_1.1.0_darwin_arm64.tar.gz"
      sha256 "f57ee2da91e17ef9176a5716e2e85311e7713d59079f663625adf85e47352d8f"

      define_method(:install) do
        bin.install "lesgo"
        bin.install "server_bin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/XplnHUB/Les-Go/releases/download/v1.1.0/Les-Go_1.1.0_linux_amd64.tar.gz"
      sha256 "1a6c881d7a4205e15e2184a2e218c57983f262910363bb965ac2922de33e5ce7"
      define_method(:install) do
        bin.install "lesgo"
        bin.install "server_bin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/XplnHUB/Les-Go/releases/download/v1.1.0/Les-Go_1.1.0_linux_arm64.tar.gz"
      sha256 "0a8a3b6734c9c42394af5fc241514694f8137cb413e90ee15580f32c737af8bd"
      define_method(:install) do
        bin.install "lesgo"
        bin.install "server_bin"
      end
    end
  end
end
