# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lesgo < Formula
  desc "WhatsApp-style CLI chat with E2EE."
  homepage "https://github.com/XplnHUB/Les-Go"
  version "1.0.15"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/XplnHUB/Les-Go/releases/download/v1.0.15/Les-Go_1.0.15_darwin_amd64.tar.gz"
      sha256 "1cb2410a679a5c7ead858f8347999833da3a54cbdf64ac415ee74d2b31c85a33"

      define_method(:install) do
        bin.install "lesgo"
        bin.install "server_bin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/XplnHUB/Les-Go/releases/download/v1.0.15/Les-Go_1.0.15_darwin_arm64.tar.gz"
      sha256 "467889479db388ed44780e905cd1797689047436134ab596e1b4e267849bdedc"

      define_method(:install) do
        bin.install "lesgo"
        bin.install "server_bin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/XplnHUB/Les-Go/releases/download/v1.0.15/Les-Go_1.0.15_linux_amd64.tar.gz"
      sha256 "0dbc7bab93f011a52c9dd66b6849662282272c63b09c4dd36ac7b33c54bbae2e"
      define_method(:install) do
        bin.install "lesgo"
        bin.install "server_bin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/XplnHUB/Les-Go/releases/download/v1.0.15/Les-Go_1.0.15_linux_arm64.tar.gz"
      sha256 "ea48332009f361a5d59bb70af2eefbe4f2885492d662878286ca3832c28669da"
      define_method(:install) do
        bin.install "lesgo"
        bin.install "server_bin"
      end
    end
  end
end
