# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lesgo < Formula
  desc "WhatsApp-style CLI chat with E2EE."
  homepage "https://github.com/XplnHUB/Les-Go"
  version "1.0.16"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/XplnHUB/Les-Go/releases/download/v1.0.16/Les-Go_1.0.16_darwin_amd64.tar.gz"
      sha256 "dd33a0735dd6b922e29ea58289fa229c3b035d90a603b8039c9be2bfe019b79d"

      define_method(:install) do
        bin.install "lesgo"
        bin.install "server_bin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/XplnHUB/Les-Go/releases/download/v1.0.16/Les-Go_1.0.16_darwin_arm64.tar.gz"
      sha256 "4277c03d3353068776ff17bb72b90fcb8ffa274cb8f49174c6f979fc6e3c0472"

      define_method(:install) do
        bin.install "lesgo"
        bin.install "server_bin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/XplnHUB/Les-Go/releases/download/v1.0.16/Les-Go_1.0.16_linux_amd64.tar.gz"
      sha256 "c3d8e21a1b10b1b687cfd99ebf51d4cfbbc897d48aa1228f354e1bbd8c660cd8"
      define_method(:install) do
        bin.install "lesgo"
        bin.install "server_bin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/XplnHUB/Les-Go/releases/download/v1.0.16/Les-Go_1.0.16_linux_arm64.tar.gz"
      sha256 "14081c58a578a57d111338031c439a7b6cfe65d14d0f3bc7791342ddd1203e52"
      define_method(:install) do
        bin.install "lesgo"
        bin.install "server_bin"
      end
    end
  end
end
